language: python
python:
  - "3.6"

sudo: required

services:
  - docker

before_install:
  - docker-compose --version
  - docker version


# Install Telemeta
install:
  - docker-compose pull
  - docker-compose build

script:
  - docker-compose run app pip freeze
  - docker-compose -f docker-compose.yml -f env/staging.yml up -d
  - docker-compose run app python manage.py test
  - sleep 180
  - curl --fail --retry 10 --retry-delay 5  -v $(docker-compose port nginx 8040)
  - curl --fail -v "$(docker-compose port nginx 80)/archives/items/Tests-c4_scalewav/"
  - docker-compose stop

after_failure:
  - docker-compose logs
