version: '2'
services:
    app:
        image: ircamweb/mezzo:latest-docker
        command: /bin/sh bin/app.sh --runserver
        ports:
            - "9001:8000"
        env_file:
            - 'env/dev.env'
