version: '2'
services:
    app:
        build: .
        command: /bin/sh bin/app.sh --runserver
        ports:
            - "9022:8000"
        env_file:
            - 'env/dev.env'
    var:
        volumes:
            - ./var/media:/srv/media
            - ./var/static:/srv/static

volumes:
    var: