version: '2'
services:
    nginx:
        image: nginx
        ports:
            - "8000:80"
        volumes:
            - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - var
        depends_on:
            - app

volumes:
    nginx:
